
#GitHub开源库
source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '10.0'

target 'SSHelpTools_Example' do
  pod 'SSHelpTools', :path => '../'

  target 'SSHelpTools_Tests' do
    inherit! :search_paths
    pod 'SDWebImage', '~> 4.4.3'

    pod 'FBSnapshotTestCase'
    pod 'YYKit'
    pod 'CocoaHTTPServer'
    pod 'TSHelpTool'
  end
end
