use_frameworks!

platform :ios, '9.0'

target 'SSHelpTools_Example' do
  pod 'SSHelpTools', :path => '../'

  target 'SSHelpTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
